services:
  squid:
    image: docker.io/squid:${SQUID_VERSION}-amd64
    restart: unless-stopped
    ports:
      - 3128:3128
    read_only: true
    networks:
      - external
      - squid-civicrm-app
      - squid-civicrm-supercronic
      - squid-civicrm-init
      - squid-civicrm-aqbanking
    tmpfs:
      - /tmp:rw
    healthcheck:
      test: [ "CMD", "test", "-f", "/tmp/squid.pid", "-a", "-r", "/tmp/squid.pid" ]
      interval: 5s
      timeout: 4s
      start_period: 10s
      retries: 3
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  civicrm-app:
    image: docker.io/civicrm-php-fpm:${CIVICRM_VERSION}-amd64
    restart: unless-stopped
    depends_on:
      squid:
        condition: service_healthy
      db:
        condition: service_healthy
      civicrm-init:
        condition: service_completed_successfully
    read_only: true
    volumes:
      - civicrm:/var/www/civicrm:ro
      - civicrm-public:/var/www/civicrm/public:rw
      - civicrm-private:/var/www/civicrm/private:rw
      - civicrm-ext:/var/www/civicrm/ext:rw
    environment:
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128
      no_proxy: localhost,127.0.0.1
    healthcheck:
      test: [ "CMD", "php", "/usr/bin/php-fpm_healthcheck.php" ]
      interval: 5s
      timeout: 4s
      start_period: 10s
      retries: 3
    networks:
      - squid-civicrm-app
      - civicrm-app-db
      - civicrm-app-nginx
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  civicrm-supercronic:
    image: docker.io/civicrm-supercronic:${CIVICRM_VERSION}-amd64
    restart: unless-stopped
    depends_on:
      squid:
        condition: service_healthy
      db:
        condition: service_healthy
      civicrm-init:
        condition: service_completed_successfully
    read_only: true
    volumes:
      - civicrm:/var/www/civicrm:ro
      - civicrm-public:/var/www/civicrm/public:rw
      - civicrm-private:/var/www/civicrm/private:rw
      - civicrm-ext:/var/www/civicrm/ext:rw
    environment:
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128
      no_proxy: localhost,127.0.0.1
    healthcheck:
      test: [ "CMD", "pgrep supercronic" ]
      interval: 5s
      timeout: 4s
      start_period: 4s
      retries: 3
    networks:
      - civicrm-supercronic-db
      - squid-civicrm-supercronic
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  civicrm-aqbanking:
    image: docker.io/civicrm-aqbanking:${CIVICRM_VERSION}-amd64
    restart: unless-stopped
    depends_on:
      squid:
        condition: service_healthy
      db:
        condition: service_healthy
      civicrm-init:
        condition: service_completed_successfully
    read_only: true
    volumes:
      - civicrm:/var/www/civicrm:ro
      - civicrm-public:/var/www/civicrm/public:rw
      - civicrm-private:/var/www/civicrm/private:rw
      - civicrm-ext:/var/www/civicrm/ext:rw
      - ./aqbanking:/home/civicrm/.aqbanking:rw # Persist aqbanking config
      - civicrm-aqbanking-trigger:/run/aqbanking:rw # Trigger volume
    environment:
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128
      no_proxy: localhost,127.0.0.1
    networks:
      - squid-civicrm-aqbanking
      - civicrm-aqbanking-db
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  civicrm-init:
    image: docker.io/civicrm-init:${CIVICRM_VERSION}-amd64
    restart: "no"
    depends_on:
      squid:
        condition: service_healthy
      db:
        condition: service_healthy
    read_only: true
    volumes:
      - civicrm:/var/www/civicrm:rw
      - civicrm-public:/var/www/civicrm/public:rw
      - civicrm-private:/var/www/civicrm/private:rw
      - civicrm-ext:/var/www/civicrm/ext:rw
    environment:
      http_proxy: http://squid:3128
      https_proxy: http://squid:3128
      no_proxy: localhost,127.0.0.1
      CIVICRM_DB_USER: civicrm
      CIVICRM_DB_PASSWORD: ${MYSQL_PASSWORD}
      CIVICRM_DB_HOST: db
      CIVICRM_DB_NAME: civicrm
      CIVICRM_UF_BASEURL: http://localhost:8080
      CIVICRM_LANG: de_DE
      CIVICRM_ADMIN_USER: admin
      CIVICRM_ADMIN_EMAIL: admin@example.com
      CIVICRM_ADMIN_PASSWORD: ${CIVICRM_ADMIN_PASSWORD}
      CIVICRM_CRED_KEYS: ${CIVICRM_CRED_KEYS}
      CIVICRM_SIGN_KEYS: ${CIVICRM_SIGN_KEYS}
      CIVICRM_SITE_KEY: ${CIVICRM_SITE_KEY}
    networks:
      - civicrm-init-db
      - squid-civicrm-init
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  db:
    hostname: db
    image: docker.io/library/mariadb:12.0.2
    restart: unless-stopped
    user: mysql:mysql
    read_only: true
    volumes:
      - db:/var/lib/mysql:rw
      - mysqld_run:/run/mysqld:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: civicrm
      MYSQL_USER: civicrm
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - civicrm-app-db
      - civicrm-supercronic-db
      - civicrm-init-db
      - civicrm-aqbanking-db
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  nginx:
    image: docker.io/nginxinc/nginx-unprivileged:stable
    user: 101:101
    ports:
      - 8080:8080
    read_only: true
    volumes:
      - civicrm:/var/www/civicrm:rw
      - civicrm-public:/var/www/civicrm/public:rw
      - civicrm-private:/var/www/civicrm/private:rw
      - civicrm-ext:/var/www/civicrm/ext:rw
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx_status.conf:/etc/nginx/conf.d/nginx_status.conf:ro
      - ./nginx/civicrm.conf:/etc/nginx/conf.d/civicrm.conf:ro
    depends_on:
      civicrm-app:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8081/nginx_status" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
    networks:
      - external
      - civicrm-app-nginx
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

volumes:
  db:
  mysqld_run:
  civicrm:
  civicrm-public:
  civicrm-private:
  civicrm-ext:
  civicrm-aqbanking-trigger:


networks:
  external:
  squid-civicrm-app:
    internal: true
    ipam:
      config:
        - subnet: 172.31.250.0/24
  squid-civicrm-supercronic:
    internal: true
    ipam:
      config:
        - subnet: 172.31.251.0/24
  squid-civicrm-init:
    internal: true
    ipam:
      config:
        - subnet: 172.31.252.0/24
  civicrm-app-db:
    internal: true
  civicrm-init-db:
    internal: true
  civicrm-supercronic-db:
    internal: true
  civicrm-app-nginx:
    internal: true
  squid-civicrm-aqbanking:
    internal: true
    ipam:
      config:
        - subnet: 172.31.253.0/24
  civicrm-aqbanking-db:
    internal: true
