acl whitelist_civicrm dstdomain "/etc/squid/whitelists/civicrm_whitelist.txt"

acl from_civicrm src 172.31.250.0/24
acl from_civicrm src 172.31.251.0/24
acl from_civicrm src 172.31.252.0/24

# Whitelist-Regel: nur diese Netze, nur diese Domains
http_access allow from_civicrm whitelist_civicrm
