vars:
  civicrm_version:
  civicrm_cv_version:
  civicrm_php_version:

package:
  name: civicrm
  version: ${{vars.civicrm_version}}
  epoch: 0
  description: "CiviCRM Standalone web files and init script"
  copyright:
    - license: AGPL-3.0

  dependencies:
    runtime:
      - civicrm-cli
      - gnutar
      - acl

environment:
  contents:
    packages:
      - busybox
      - curl
      - ca-certificates-bundle

pipeline:
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/civicrm
      curl -fsSL https://download.civicrm.org/civicrm-${{vars.civicrm_version}}-standalone.tar.gz -o ${{targets.destdir}}/usr/share/civicrm/civicrm.tar.gz
      echo "AGPL-3.0" > ${{targets.destdir}}/usr/share/civicrm/LICENSE
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      cp civicrm_init.sh ${{targets.destdir}}/usr/bin/civicrm_init.sh
      chmod +x ${{targets.destdir}}/usr/bin/civicrm_init.sh
  - runs: |
      mkdir -p ${{targets.destdir}}/var/www/civicrm/public ${{targets.destdir}}/var/www/civicrm/private ${{targets.destdir}}/var/www/civicrm/ext

subpackages:

  - name: civicrm-cli
    description: "CiviCRM command line tools"

    pipeline:
      - runs: |
          # Download cv (https://github.com/civicrm/cv)
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          curl -fLsS https://github.com/civicrm/cv/releases/download/v${{vars.civicrm_cv_version}}/cv-${{vars.civicrm_cv_version}}.phar -o ${{targets.subpkgdir}}/usr/bin/cv
          chmod +x ${{targets.subpkgdir}}/usr/bin/cv

    dependencies:
      runtime:
      - php-${{vars.civicrm_php_version}}
      - php-${{vars.civicrm_php_version}}-bcmath
      - php-${{vars.civicrm_php_version}}-curl
      - php-${{vars.civicrm_php_version}}-dom
      - php-${{vars.civicrm_php_version}}-fileinfo
      - php-${{vars.civicrm_php_version}}-iconv
      - php-${{vars.civicrm_php_version}}-intl
      - php-${{vars.civicrm_php_version}}-mbstring
      - php-${{vars.civicrm_php_version}}-mysqli
      - php-${{vars.civicrm_php_version}}-mysqlnd
      - php-${{vars.civicrm_php_version}}-openssl
      - php-${{vars.civicrm_php_version}}-phar
      - php-${{vars.civicrm_php_version}}-simplexml
      - php-${{vars.civicrm_php_version}}-xml
      - php-${{vars.civicrm_php_version}}-zip

  - name: civicrm-php-fpm
    description: "PHP-FPM with civicrm flavor"

    pipeline:
      - runs: |
          # copy PHP-FPM config for CiviCRM
          mkdir -p ${{targets.subpkgdir}}/etc/php/php-fpm.d
          cp civicrm_php-fpm.conf ${{targets.subpkgdir}}/etc/php/php-fpm.d/zzz-civicrm.conf
      - runs: |
          # copy PHP INI config for CiviCRM
          mkdir -p ${{targets.subpkgdir}}/etc/php/conf.d
          cp civicrm_php.ini ${{targets.subpkgdir}}/etc/php/conf.d/99-civicrm.ini
      - runs: |
          # copy entrypoint script
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          cp civicrm_init_php-fpm_healthchecks.sh ${{targets.subpkgdir}}/usr/bin/civicrm_init_php-fpm_healthchecks.sh
          chmod +x ${{targets.subpkgdir}}/usr/bin/civicrm_init_php-fpm_healthchecks.sh
      - runs: |
          # copy healthcheck script
          cp php-fpm_healthcheck.php ${{targets.subpkgdir}}/usr/bin/php-fpm_healthcheck.php
          chmod +x ${{targets.subpkgdir}}/usr/bin/php-fpm_healthcheck.php
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/run/php

    dependencies:
      runtime:
      - php-${{vars.civicrm_php_version}}
      - php-${{vars.civicrm_php_version}}-bcmath
      - php-${{vars.civicrm_php_version}}-curl
      - php-${{vars.civicrm_php_version}}-dom
      - php-${{vars.civicrm_php_version}}-fileinfo
      - php-${{vars.civicrm_php_version}}-fpm
      - php-${{vars.civicrm_php_version}}-gd
      - php-${{vars.civicrm_php_version}}-imagick
      - php-${{vars.civicrm_php_version}}-intl
      - php-${{vars.civicrm_php_version}}-mbstring
      - php-${{vars.civicrm_php_version}}-mysqli
      - php-${{vars.civicrm_php_version}}-mysqlnd
      - php-${{vars.civicrm_php_version}}-simplexml
      - php-${{vars.civicrm_php_version}}-xml
      - php-${{vars.civicrm_php_version}}-zip
#      - wkhtmltopdf  # maybe be need to build our own wkhtmltopdf package

  - name: civicrm-supercronic
    description: "Supercronic with civicrm flavor"

    pipeline:
      - runs: |
          # copy crontab
          mkdir -p ${{targets.subpkgdir}}/etc/supercronic
          cp crontab ${{targets.subpkgdir}}/etc/supercronic/crontab

    dependencies:
      runtime:
      - supercronic
      - civicrm-cli