pid_filename /tmp/squid.pid

http_port 3128
visible_hostname squid

# Logging ohne root
access_log stdio:/dev/stdout
cache_log stdio:/dev/stderr

# Kein Cache (Whitelist-Proxy)
cache deny all

# Ports
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

# Methoden
acl allowed_methods method CONNECT GET HEAD
http_access deny !allowed_methods

# Portsicherheit
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# Optional: Host-Verifikation
host_verify_strict on

# Service-spezifische ACls / Regeln
include /etc/squid/conf.d/*.conf

# Default deny
http_access deny all
